import { AggregateRoot, UniqueId, Result } from '../../../../shared/kernel';
import { Dimensions } from '../value-objects/Dimensions';
import { MaterialSku } from '../value-objects/MaterialSku';
import { CuttingOptimizationCompletedEvent } from '../events/CuttingOptimizationCompletedEvent';
import { WorkOrderCompletedEvent } from '../events/WorkOrderCompletedEvent';

// ── Supporting types ──────────────────────────────────────────────────────────

/** A piece required by the work order — input to the cutting engine. */
export interface CuttingRequirement {
  readonly id:          string;       // stable identifier used by Python engine
  readonly materialSku: MaterialSku;
  readonly dimensions:  Dimensions;
  readonly quantity:    number;
  readonly label:       string;       // e.g. "Panel lateral cajón"
}

/** A single piece placement within a board/offcut. */
export interface PiecePlacement {
  readonly requirementId: string;
  readonly x:             number;
  readonly y:             number;
  readonly widthMm:       number;
  readonly heightMm:      number;
  readonly rotated:       boolean;
}

/** Offcut generated by the cutting engine after using a board. */
export interface PlannedOffcut {
  readonly widthMm:  number;
  readonly heightMm: number;
  readonly x:        number;
  readonly y:        number;
}

/** Per-board allocation produced by the Python cutting engine. */
export interface BoardAllocation {
  readonly boardId:       string;         // Board or Offcut id
  readonly isOffcut:      boolean;        // true → se tomó de un Offcut existente
  readonly placements:    PiecePlacement[];
  readonly offcuts:       PlannedOffcut[]; // retazos que quedarán
}

/** Full result returned by the Python cutting engine, stored inside WorkOrder. */
export interface CuttingPlan {
  readonly efficiencyPercent: number;
  readonly boardAllocations:  BoardAllocation[];
  readonly svgLayout:         string;   // diagrama SVG del corte
  readonly unplacedPieceIds:  string[]; // vacío si éxito completo
  readonly computedAt:        Date;
}

// ── Status enum with strict transition guard ──────────────────────────────────

export enum WorkOrderStatus {
  PENDING     = 'PENDING',    // creada, esperando optimización
  OPTIMIZING  = 'OPTIMIZING', // motor Python en progreso / plan calculado
  CUTTING     = 'CUTTING',    // operario ejecutando el corte físico
  COMPLETED   = 'COMPLETED',  // materiales descontados, retazos registrados
  CANCELLED   = 'CANCELLED',  // cancelada, reservas liberadas
}

const ALLOWED_TRANSITIONS: Record<WorkOrderStatus, WorkOrderStatus[]> = {
  [WorkOrderStatus.PENDING]:    [WorkOrderStatus.OPTIMIZING, WorkOrderStatus.CANCELLED],
  [WorkOrderStatus.OPTIMIZING]: [WorkOrderStatus.CUTTING,    WorkOrderStatus.CANCELLED],
  [WorkOrderStatus.CUTTING]:    [WorkOrderStatus.COMPLETED,  WorkOrderStatus.CANCELLED],
  [WorkOrderStatus.COMPLETED]:  [],
  [WorkOrderStatus.CANCELLED]:  [],
};

// ── WorkOrder props ───────────────────────────────────────────────────────────

interface WorkOrderProps {
  productName:   string;
  requirements:  CuttingRequirement[];
  status:        WorkOrderStatus;
  cuttingPlan:   CuttingPlan | null;
  /** IDs of boards/offcuts reserved for this order (populated after optimization). */
  reservedStockIds: string[];
  createdAt:     Date;
  updatedAt:     Date;
  completedAt:   Date | null;
}

// ── Aggregate ─────────────────────────────────────────────────────────────────

/**
 * WorkOrder — Aggregate Root.
 *
 * Represents a manufacturing order with a set of cutting requirements.
 * Orchestration flow (driven by ExecuteCuttingOptimization use-case):
 *
 *   PENDING → [Python engine call] → OPTIMIZING
 *                                       │
 *                            (operario confirma corte)
 *                                       ↓
 *                                   CUTTING → COMPLETED
 *
 * Domain events emitted:
 *   • CuttingOptimizationCompletedEvent  (→ Kafka: scm.workorder.cutting_completed)
 *   • WorkOrderCompletedEvent            (→ Kafka: scm.workorder.completed)
 *
 * These events are consumed by the InventoryTransactionHandler to:
 *   - Persist offcuts as new Offcut entities
 *   - Mark boards/offcuts as CONSUMED
 */
export class WorkOrder extends AggregateRoot<WorkOrderProps> {

  // ── Factory ──────────────────────────────────────────────────────────────────

  static create(
    tenantId: string,
    raw: {
      productName:  string;
      requirements: CuttingRequirement[];
    },
  ): Result<WorkOrder> {
    if (!raw.productName.trim())
      return Result.fail('productName is required');
    if (raw.requirements.length === 0)
      return Result.fail('WorkOrder must have at least one cutting requirement');

    // Validate all requirements have positive quantities
    const invalid = raw.requirements.find(r => r.quantity <= 0);
    if (invalid)
      return Result.fail(`Requirement "${invalid.label}" has invalid quantity ${invalid.quantity}`);

    const now = new Date();
    return Result.ok(
      new WorkOrder(UniqueId.create(), tenantId, {
        productName:      raw.productName,
        requirements:     raw.requirements,
        status:           WorkOrderStatus.PENDING,
        cuttingPlan:      null,
        reservedStockIds: [],
        createdAt:        now,
        updatedAt:        now,
        completedAt:      null,
      }),
    );
  }

  static reconstitute(id: string, tenantId: string, props: WorkOrderProps): WorkOrder {
    return new WorkOrder(UniqueId.from(id), tenantId, props);
  }

  // ── Getters ──────────────────────────────────────────────────────────────────

  get productName():       string               { return this.props.productName; }
  get requirements():      CuttingRequirement[] { return [...this.props.requirements]; }
  get status():            WorkOrderStatus      { return this.props.status; }
  get cuttingPlan():       CuttingPlan | null   { return this.props.cuttingPlan; }
  get reservedStockIds():  string[]             { return [...this.props.reservedStockIds]; }
  get createdAt():         Date                 { return this.props.createdAt; }
  get updatedAt():         Date                 { return this.props.updatedAt; }
  get completedAt():       Date | null          { return this.props.completedAt; }

  // ── State machine ─────────────────────────────────────────────────────────────

  private transition(to: WorkOrderStatus): Result<void> {
    const allowed = ALLOWED_TRANSITIONS[this.props.status];
    if (!allowed.includes(to))
      return Result.fail(
        `Illegal WorkOrder transition: ${this.props.status} → ${to}`,
      );
    this.props.status    = to;
    this.props.updatedAt = new Date();
    return Result.ok(undefined);
  }

  /**
   * Called by ExecuteCuttingOptimizationUseCase after receiving the Python engine response.
   * Attaches the CuttingPlan and transitions to OPTIMIZING.
   * Emits CuttingOptimizationCompletedEvent.
   */
  attachCuttingPlan(plan: CuttingPlan, reservedStockIds: string[]): Result<void> {
    const t = this.transition(WorkOrderStatus.OPTIMIZING);
    if (t.isFail()) return t;

    this.props.cuttingPlan      = plan;
    this.props.reservedStockIds = reservedStockIds;

    this.addDomainEvent(
      new CuttingOptimizationCompletedEvent(this.tenantId, {
        workOrderId:        this.id.toString(),
        productName:        this.props.productName,
        efficiencyPercent:  plan.efficiencyPercent,
        boardsUsed:         plan.boardAllocations.length,
        offcutsGenerated:   plan.boardAllocations.reduce((s, b) => s + b.offcuts.length, 0),
        unplacedPieceIds:   plan.unplacedPieceIds,
        svgLayout:          plan.svgLayout,
      }),
    );

    return Result.ok(undefined);
  }

  /** Transitions to CUTTING — operario has started physical cutting. */
  startCutting(): Result<void> {
    return this.transition(WorkOrderStatus.CUTTING);
  }

  /**
   * Called after the operario finishes physical cutting.
   * Transitions to COMPLETED and emits WorkOrderCompletedEvent.
   * The event payload carries board/offcut IDs so the handler can update inventory.
   */
  complete(): Result<void> {
    if (!this.props.cuttingPlan)
      return Result.fail('Cannot complete WorkOrder without a cutting plan');

    const t = this.transition(WorkOrderStatus.COMPLETED);
    if (t.isFail()) return t;

    this.props.completedAt = new Date();

    this.addDomainEvent(
      new WorkOrderCompletedEvent(this.tenantId, {
        workOrderId:     this.id.toString(),
        productName:     this.props.productName,
        reservedStockIds: this.props.reservedStockIds,
        boardAllocations: this.props.cuttingPlan.boardAllocations,
      }),
    );

    return Result.ok(undefined);
  }

  cancel(): Result<void> {
    return this.transition(WorkOrderStatus.CANCELLED);
  }
}
